name = "CayleyMengerDeterminant"
uuid = "5b98d230-66e3-4a60-a8a7-ae961925db22"
authors = ["Alexander Ronald Altman <alexanderaltman@me.com>"]
version = "0.3.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArrayInterface = "5.0.7, 6"
InverseFunctions = "0.1.3"
Static = "0.4.1 - 0.6"
StaticArrays = "1.4.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
